FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    pkg-config \
    libsdl2-dev \
    libgl-dev \
    libglm-dev \
    libpq-dev \
    python3 \
    python3-pip \
    pipx \
    && rm -rf /var/lib/apt/lists/*

USER 1000:1000

WORKDIR /src
